import os

ENV = os.getenv('ENV')
AWS_ACCOUNT_ID = "802430592232"
AWS_REGION = "us-west-2"
PROJECT_NAME = "cdk-bastion"

# Bastion
BASTION_STACK_NAME = f"{PROJECT_NAME}-bastion"
BASTION_VPC_NAME = f"{BASTION_STACK_NAME}-vpc"
ADMIN_USER_NAME = f"{BASTION_STACK_NAME}-admin"
ADMIN_USER_ACCESS_KEY_ID_SSM = f"{BASTION_STACK_NAME}-admin-access-key-id"
ADMIN_USER_ACCESS_KEY_SECRET_SSM = f"{BASTION_STACK_NAME}-admin-access-key-secret"
BASTION_INSTANCE_NAME = f"{BASTION_STACK_NAME}-instance"
BASTION_INSTANCE_TYPE = "t2.micro"
